databases:
  - name: microscope_project_db
    plan: free
    databaseName: microscope_project
    user: microscope_project

services:
  - type: web
    plan: free
    name: microscope_project
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn microscope_project.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: microscope_project_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: 0
